// Unity Physics Backend System Native Plugin API Data Protocol copyright © 2025 Unity Technologies ApS
//
// Licensed under the Unity Companion License for Unity - dependent projects--see[Unity Companion License](http://www.unity3d.com/legal/licenses/Unity_Companion_License).
//
// Unless expressly provided otherwise, the Software under this license is made available strictly on an “AS IS” BASIS WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.Please review the license for details on these and other terms and conditions.
//
// Please note that the following data protocol types represent the data used internally by Unity's Physics Module in order to communicate with the current SDK Integration. As such these types are subject to rapid change between different Unity versions.

#pragma  once
#include <cstdint>
#include <type_traits>
#include "PhysicsCommonTypes.h"
#include "PhysicsVecTypes.h"

namespace Physics
{
    // A single contact point generated by the solver during collision detection.
    // Contains the world-space contact position, penetration depth (separation),
    // contact normal, accumulated impulse, and the triangle face indices on each shape.
    struct ContactPoint
    {
        Vec3 position;
        float separation;
        Vec3 normal;
        uint32_t faceIndex0;
        Vec3 impulse;
        uint32_t faceIndex1;
    };

    // Status flags for a body pair in the simulation results, indicating whether
    // either actor was removed during the simulation step.
    enum class BodyPairFlags : uint16_t
    {
        Invalid = 0,
        RemovedActor = 1 << 0,
        RemovedOtherActor = 1 << 1
    };

    // Per-shape-pair status flags within a body pair, indicating shape removal,
    // first/lost touch transitions, and internal solver state.
    enum class ShapePairFlags : uint16_t
    {
        Invalid = 0,
        RemovedShape = 1 << 0,                // This shape was removed during simulation
        RemovedOtherShape = 1 << 1,           // The other shape was removed during simulation
        ActorPairHasFirstTouch = 1 << 2,      // First frame of contact between these actors
        ActorPairLostTouch = 1 << 3,          // Actors separated this frame
        InternalHasImpulses = 1 << 4,         // Contact has non-zero impulse data
        InternalContactAreFlipped = 1 << 5    // Contact normal direction is flipped relative to shape order
    };

    // Bitmask configuring which collision events a shape pair can generate.
    // Set via SetSupportedMessages and stored in FilterData::pairFlags.
    enum class ShapePairEventFlags : uint16_t // Size is important!
    {
        None = 0,
        SolveContact = 1 << 0,                 // Generate solver contacts (enables physical response)
        ModifyContacts = 1 << 1,               // Allow runtime contact modification via callback
        NotifyTouchFound = 1 << 2,             // Report when shapes first start touching
        NotifyTouchPersists = 1 << 3,          // Report every frame that shapes remain in contact
        NotifyTouchLost = 1 << 4,              // Report when shapes stop touching
        NotifyTouchCCD = 1 << 5,               // Report CCD (continuous collision detection) touch events
        NotifyThresholdForceFound = 1 << 6,    // Report when contact force exceeds threshold (first frame)
        NotifyThresholdForcePersists = 1 << 7, // Report every frame force exceeds threshold
        NotifyThresholdForceLost = 1 << 8,     // Report when contact force drops below threshold
        NotifyContactPoints = 1 << 9,          // Include individual contact point data in reports
        DetectDiscreteContact = 1 << 10,       // Enable discrete contact detection for this pair
        DetectCCDContact = 1 << 11,            // Enable CCD contact detection for this pair
        PreSolverVelocity = 1 << 12,           // Include pre-solver velocity data in contact reports
        PostSolvedVelocity = 1 << 13,          // Include post-solver velocity data in contact reports
        ContactEventPose = 1 << 14,            // Include actor poses in contact event reports
        NextFree = 1 << 15,

        ContactDefault = SolveContact | DetectDiscreteContact,
        TriggerDefault = NotifyTouchFound | NotifyTouchLost | DetectDiscreteContact
    };

    inline constexpr ShapePairEventFlags operator & (ShapePairEventFlags lhs, ShapePairEventFlags rhs)
    {
        using type_t = std::underlying_type_t<ShapePairEventFlags>;
        return static_cast<ShapePairEventFlags>(static_cast<type_t>(lhs) & static_cast<type_t>(rhs));
    }

    inline constexpr ShapePairEventFlags operator | (ShapePairEventFlags lhs, ShapePairEventFlags rhs)
    {
        using type_t = std::underlying_type_t<ShapePairEventFlags>;
        return static_cast<ShapePairEventFlags>(static_cast<type_t>(lhs) | static_cast<type_t>(rhs));
    }

    inline constexpr ShapePairEventFlags& operator |= (ShapePairEventFlags& lhs, ShapePairEventFlags rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    inline constexpr ShapePairEventFlags operator ~ (ShapePairEventFlags rhs)
    {
        using type_t = std::underlying_type_t<ShapePairEventFlags>;
        return static_cast<ShapePairEventFlags>(~static_cast<type_t>(rhs));
    }

    inline constexpr ShapePairEventFlags& operator &= (ShapePairEventFlags& lhs, ShapePairEventFlags rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    // A collision pair between two shapes, containing the collider IDs, a pointer to the array of
    // contact points, pair status flags, event flags, and the total impulse sum across all contacts.
    struct ShapePair
    {
        EntityId thisColliderID;
        EntityId otherColliderID;
        ContactPoint* startPtr;
        uint32_t nbPoints;
        ShapePairFlags flags;
        ShapePairEventFlags events;
        Vec3 impulseSum;
    };

    // A collision pair between two bodies, containing the body IDs, a pointer to the array of
    // shape pairs, pair status flags, and the pre-solve linear and angular velocities of both bodies.
    struct BodyPair
    {
        EntityId thisBodyID;
        EntityId otherBodyID;
        ShapePair* startPtr;
        uint32_t nbPairs;
        BodyPairFlags flags;
        Vec3 thisBodyLinearVelocity;
        Vec3 thisBodyAngularVelocity;
        Vec3 otherBodyLinearVelocity;
        Vec3 otherBodyAngularVelocity;
    };

    // Classifies a trigger event as entering or exiting the trigger volume.
    enum class TriggerEventType
    {
        Invalid,
        Enter, // A collider entered the trigger volume
        Exit,  // A collider exited the trigger volume
    };

    // Reports a trigger overlap event between a trigger shape and a collider shape.
    // Includes SDK handles for both shapes and engine-side entity IDs for the trigger and collider.
    struct TriggerEvent
    {
        SDKObjectHandle triggerShape;
        SDKObjectHandle colliderShape;
        EntityId trigger;
        EntityId collider;
        TriggerEventType type;

        TriggerEvent(TriggerEventType evt, SDKObjectHandle sdkTrigger, SDKObjectHandle sdkCollider, EntityId triggerID, EntityId colliderID)
            : type(evt)
            , triggerShape(sdkTrigger)
            , colliderShape(sdkCollider)
            , trigger(triggerID)
            , collider(colliderID)
        {}
    };

    // Reports that a joint has broken because its constraint force or torque exceeded the break thresholds.
    struct JointBreakEvent
    {
        EntityId jointID;
        float linearMagnitude;   // Magnitude of the linear force that caused the break
        float angularMagnitude;  // Magnitude of the angular torque that caused the break
    };
}
